version: '3:9'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - 8000:8000
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django_gunicorn
    restart: always

volumes:
  static:
