# Generated by Django 4.1.1 on 2022-10-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Пакет услуг', 'verbose_name_plural': 'Пакеты услуг'},
        ),
    ]
