# Generated by Django 4.1.1 on 2022-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_css_alter_cmsslider_cms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(upload_to='sliderimg/', verbose_name='Слайд'),
        ),
    ]
