# Generated by Django 4.1.1 on 2022-10-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_cmsslider_cms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(default='-', null=True, upload_to='sliderimg/', verbose_name='Слайд'),
        ),
    ]
